import { TankProps } from "./types";

export const tanks: TankProps[] = [
     {
          color: "#038aff",
          fillMaxValue: 100,
          clName: "tank1",
          title: "Line 1",
          backFontColor: "#fe7968",
          fillValue: 50,
          type: "normal",
     },
     {
          color: "#038aff",
          fillMaxValue: 100,
          clName: "tank2",
          title: "Line 2",
          backFontColor: "#fe7968",
          fillValue: 60,
          type: "normal",
     },
     {
          color: "#038aff",
          fillMaxValue: 100,
          clName: "tank3",
          title: "Line 3",
          backFontColor: "#fe7968",
          fillValue: 90,
          type: "normal",
     },
     {
          color: "#038aff",
          fillMaxValue: 100,
          clName: "tank4",
          title: "Line 4",
          backFontColor: "#fe7968",
          fillValue: 30,
          type: "normal",
     },
     {
          color: "#038aff",
          fillMaxValue: 100,
          clName: "tank5",
          title: "Line 5",
          backFontColor: "#fe7968",
          fillValue: 10,
          type: "normal",
     },
     {
          color: "#038aff",
          fillMaxValue: 100,
          clName: "tank6",
          title: "Line 6",
          backFontColor: "#fe7968",
          fillValue: 50,
          type: "normal",
     },
     {
          color: "#038aff",
          fillMaxValue: 100,
          clName: "tank7",
          title: "Line 7",
          backFontColor: "#fe7968",
          fillValue: 40,
          type: "normal",
     },
     {
          color: "#038aff",
          fillMaxValue: 100,
          clName: "tank8",
          title: "Line 8",
          backFontColor: "#fe7968",
          fillValue: 80,
          type: "normal",
     },
     {
          color: "#038aff",
          fillMaxValue: 100,
          clName: "tank9",
          title: "Line 9",
          backFontColor: "#fe7968",
          fillValue: 70,
          type: "normal",
     },
     {
          color: "#038aff",
          fillMaxValue: 100,
          clName: "tank10",
          title: "Line 10",
          backFontColor: "#fe7968",
          fillValue: 20,
          type: "normal",
     },
     {
          color: "#038aff",
          fillMaxValue: 100,
          clName: "tank11",
          title: "Line 11",
          backFontColor: "#fe7968",
          fillValue: 50,
          type: "normal",
     },
     {
          color: "#038aff",
          fillMaxValue: 100,
          clName: "tank12",
          title: "Line 12",
          backFontColor: "#fe7968",
          fillValue: 45,
          type: "normal",
     },
     {
          color: "#038aff",
          fillMaxValue: 100,
          clName: "tank20",
          title: "T11",
          backFontColor: "#fe7968",
          fillValue: 70,
          type: "premix",
          temperature: 55,
          minimumTemperature: 60,
          temperatureMsm: "celcius",
          temperatureColor: "#DC3545",
     },
     {
          color: "#038aff",
          fillMaxValue: 100,
          clName: "tank21",
          title: "T11",
          backFontColor: "#fe7968",
          fillValue: 90,
          type: "premix",
          temperature: 30,
          minimumTemperature: 5,
          temperatureMsm: "celcius",
          temperatureColor: "#DC3545",
     },
     {
          color: "#038aff",
          fillMaxValue: 100,
          clName: "tank23",
          title: "T11",
          backFontColor: "#fe7968",
          fillValue: 10,
          type: "premix",
          temperature: 15,
          minimumTemperature: 10,
          temperatureMsm: "celcius",
          temperatureColor: "#DC3545",
     },
     {
          color: "#038aff",
          fillMaxValue: 100,
          clName: "tank24",
          title: "T11",
          backFontColor: "#fe7968",
          fillValue: 30,
          type: "mix",
          temperature: 45,
          minimumTemperature: 10,
          temperatureMsm: "celcius",
          temperatureColor: "#DC3545",
     },
     {
          color: "#038aff",
          fillMaxValue: 100,
          clName: "tank25",
          title: "T11",
          backFontColor: "#fe7968",
          fillValue: 66,
          type: "mix",
          temperature: 13,
          minimumTemperature: 10,
          temperatureMsm: "celcius",
          temperatureColor: "#DC3545",
     },
     {
          color: "#038aff",
          fillMaxValue: 100,
          clName: "tank26",
          title: "T11",
          backFontColor: "#fe7968",
          fillValue: 81,
          type: "mix",
          temperature: 22,
          minimumTemperature: 10,
          temperatureMsm: "celcius",
          temperatureColor: "#DC3545",
     },
];

export const tabs = ["Home", "Pre Mix/Mixing"];
